In [ ]:
#. Import the numpy package under the name np
import numpy as np

In [2]:
#Print the numpy version and the configuration
import numpy as np

print("Numpy version:", np.__version__)
print("Numpy configuration:")
np.show_config()

In [ ]:
#Create a null vector of size 10
import numpy as np

null_vector = np.zeros(10)
print(null_vector)

In [ ]:
#How to find the memory size of any array
import numpy as np

# Create a numpy array
arr = np.array([1, 2, 3, 4, 5])

# Print the memory size of the array in bytes
print(arr.nbytes)

In [7]:
#5. How to get the documentation of the numpy add function from the command line?
import numpy as np
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [1]:
#6. Create a null vector of size 10 but the fifth value which is 1
import numpy as np

# Create a null vector of size 10
vector = np.zeros(10)

# Set the fifth value to 1
vector[4] = 1  # Indexing in Python starts from 0

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#7Create a vector with values ranging from 10 to 49
import numpy as np

# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [1]:
#8. Reverse a vector (first element becomes last)
import numpy as np

# Create a vector
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[5 4 3 2 1]


In [2]:
#Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np

# Create an array with values from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

# Define the array
array = np.array([1,2,0,0,4,0])

# Find the indices of non-zero elements
indices = np.nonzero(array)

print(indices)

(array([0, 1, 4]),)


In [8]:
#11. Create a 3x3 identity matrix

import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#12. Create a 3x3x3 array with random values

import numpy as np

# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))

print(random_array)

[[[0.3435155  0.28442808 0.19180276]
  [0.52447876 0.64623067 0.69757022]
  [0.95505359 0.49500567 0.51402574]]

 [[0.60331462 0.14772076 0.69374476]
  [0.99587642 0.21591454 0.59963855]
  [0.11410946 0.03985319 0.00970132]]

 [[0.03805866 0.91693106 0.60535464]
  [0.9663552  0.44928147 0.08476728]
  [0.24987931 0.2086925  0.5640391 ]]]


In [11]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Minimum Value: ", min_value)
print("Maximum Value: ", max_value)

Minimum Value:  0.019733639177200724
Maximum Value:  0.9914137048092152


In [12]:
#14. Create a random vector of size 30 and find the mean value
import numpy as np

# Create a random vector of size 30
random_vector = np.random.random(30)

# Find the mean value
mean_value = random_vector.mean()

print("Mean Value: ", mean_value)

Mean Value:  0.48424281501207656


In [14]:
#15. Create a 2d array with 1 on the border and 0 inside
import numpy as np

# Create a 2D array with ones
array = np.ones((5, 5))

# Set the interior of the array to zero
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#16. How to add a border (filled with 0's) around an existing array?
import numpy as np

# Create an existing array
array = np.ones((3, 3))

# Add a border filled with 0's around the existing array
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(array_with_border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

print(0 * np.nan)           # nan
print(np.nan == np.nan)     # False
print(np.inf > np.nan)      # False
print(np.nan - np.nan)      # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)      # False

nan
False
False
nan
True
False


In [18]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern

import numpy as np

# Create an 8x8 matrix
matrix = np.zeros((8,8), dtype=int)

# Fill it with a checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np

# Find the index (x,y,z) of the 100th element in a (6,7,8) shape array
index = np.unravel_index(99, (6,7,8))

print(index)

(1, 5, 3)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function
import numpy as np

# Create a 2x2 matrix for the base pattern
pattern = np.array([[0, 1], [1, 0]])

# Create a checkerboard 8x8 matrix using the tile function
checkerboard = np.tile(pattern, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#22. Normalize a 5x5 random matrix
matrix = np.random.random((5, 5))

# Normalize the matrix
min_val = matrix.min()
max_val = matrix.max()
normalized_matrix = (matrix - min_val) / (max_val - min_val)
print(normalized_matrix)


[[0.14356324 0.04596715 0.48757684 0.54651855 0.81983402]
 [0.70439147 0.         0.4895509  0.07192048 1.        ]
 [0.06234933 0.27965662 0.7841554  0.66554645 0.64428648]
 [0.57741254 0.35782736 0.83412529 0.53774189 0.72371091]
 [0.60233988 0.57371529 0.44058818 0.77399256 0.14238018]]


In [24]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
import numpy as np

# Create a custom dtype for RGBA
rgba_dtype = np.dtype([('R', np.ubyte, 1),
                       ('G', np.ubyte, 1),
                       ('B', np.ubyte, 1),
                       ('A', np.ubyte, 1)])

print(rgba_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


/var/folders/9y/8rjmtst10lq0t833bkn_ks9w0000ks/T/ipykernel_24311/2827847434.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  rgba_dtype = np.dtype([('R', np.ubyte, 1),


In [25]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
import numpy as np

# Create a 5x3 matrix
matrix1 = np.random.random((5, 3))

# Create a 3x2 matrix
matrix2 = np.random.random((3, 2))

# Multiply the matrices
product = matrix1 @ matrix2

print(product)

[[0.65245481 0.49330607]
 [0.48359457 0.34644956]
 [0.9823522  0.58464639]
 [1.29876237 0.75864564]
 [0.38628198 0.22385095]]


In [26]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place. 
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Negate all elements which are between 3 and 8, in place
array[(array > 3) & (array < 8)] *= -1

print(array)

[ 1  2  3 -4 -5 -6 -7  8  9]


In [27]:
#26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [29]:
#27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

"""Assuming Z is a numpy array of integers, here's the legality of each expression:

Z**Z: Legal. Each element in the array is raised to the power of itself.
2 << Z >> 2: Legal. Bit-shifts each element in the array to the left by 2 bits, then to the right by 2 bits.
Z <- Z: Legal. Checks if each element in the array is less than negative of itself. Returns an array of booleans.
1j*Z: Legal. Multiplies each element in the array by 1j (complex number).
Z/1/1: Legal. Divides each element in the array by 1 twice.
Z<Z>Z: Illegal. Python doesn't allow chaining of comparison operators in this way.
Please note that the legality of these expressions can depend on the actual values in Z. For example, 2 << Z >> 2 could raise a ValueError if Z contains negative numbers."""

NameError: name 'Z' is not defined

In [30]:
#28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/9y/8rjmtst10lq0t833bkn_ks9w0000ks/T/ipykernel_24311/330620176.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/9y/8rjmtst10lq0t833bkn_ks9w0000ks/T/ipykernel_24311/330620176.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/9y/8rjmtst10lq0t833bkn_ks9w0000ks/T/ipykernel_24311/330620176.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [31]:
#29. How to round away from zero a float array ?
import numpy as np

# Create a float array
array = np.array([-1.7, -0.2, 0.2, 1.7])

# Round away from zero
rounded_array = np.copysign(np.ceil(np.fabs(array)), array)

print(rounded_array)

[-2. -1.  1.  2.]


In [32]:
#30. How to find common values between two arrays? 
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values between the arrays
common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


In [33]:
#31. How to ignore all numpy warnings (not recommended)?
import numpy as np

# Ignore all numpy warnings
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [34]:
#32. Is the following expressions true? 
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [35]:
#33. How to get the dates of yesterday, today and tomorrow?
import numpy as np

# Get the date of today
today = np.datetime64('today', 'D')

# Get the date of yesterday
yesterday = today - np.timedelta64(1, 'D')

# Get the date of tomorrow
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday: ", yesterday)
print("Today: ", today)
print("Tomorrow: ", tomorrow)

Yesterday:  2024-06-18
Today:  2024-06-19
Tomorrow:  2024-06-20


In [36]:
#34. How to get all the dates corresponding to the month of July 2016?

import numpy as np

# Get all the dates for the month of July 2016
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(dates_july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [38]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?



# Create arrays A and B
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [39]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
import numpy as np

# Create a random array of positive numbers
array = np.random.uniform(0, 10, 5)

print("Original array: ", array)

# Method 1: Using astype(int)
print("Method 1: ", array.astype(int))

# Method 2: Using trunc
print("Method 2: ", np.trunc(array))

# Method 3: Using floor
print("Method 3: ", np.floor(array))

# Method 4: Using the integer division operator
print("Method 4: ", array // 1)

Original array:  [3.175206   4.62781915 7.74708796 1.60055129 5.43394164]
Method 1:  [3 4 7 1 5]
Method 2:  [3. 4. 7. 1. 5.]
Method 3:  [3. 4. 7. 1. 5.]
Method 4:  [3. 4. 7. 1. 5.]


In [40]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4

import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(np.arange(0, 5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [42]:
#38. Consider a generator function that generates 10 integers and use it to build an array

import numpy as np

# Create a generator function that generates 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Use the generator function to build an array
array = np.fromiter(generate_integers(), dtype=int)

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [44]:
#40. Create a random vector of size 10 and sort it

import numpy as np

# Create a random vector of size 10
vector = np.random.random(10)

# Sort the vector
sorted_vector = np.sort(vector)

print(sorted_vector)

[0.04722437 0.15708638 0.30363464 0.45234259 0.71707959 0.72275226
 0.79004189 0.83123765 0.91602657 0.92277903]


In [45]:
#41. How to sum a small array faster than np.sum?
import numpy as np

# Create a small array
array = np.array([1, 2, 3, 4, 5])

# Sum the array using Python's built-in sum function
sum_array = sum(array)

print(sum_array)

15


In [46]:
#42. Consider two random array A and B, check if they are equal
import numpy as np

# Create two random arrays A and B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("A: ", A)
print("B: ", B)
print("Are A and B equal? ", are_equal)

A:  [1 1 1 1 1]
B:  [0 1 1 1 1]
Are A and B equal?  False


In [47]:
#43. Make an array immutable (read-only)

import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Make the array immutable (read-only)
array.flags.writeable = False

# Try to modify the array
try:
    array[0] = 10
except ValueError as e:
    print(e)

assignment destination is read-only


In [48]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

import numpy as np

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.random((10, 2))

# Convert the Cartesian coordinates to polar coordinates
r = np.hypot(cartesian_coords[:, 0], cartesian_coords[:, 1])
theta = np.arctan2(cartesian_coords[:, 1], cartesian_coords[:, 0])

polar_coords = np.column_stack((r, theta))

print(polar_coords)


[[1.06195753 1.19904851]
 [0.79392185 0.66253341]
 [1.14195283 1.03161494]
 [0.95931528 1.15563159]
 [0.20533177 0.4786893 ]
 [0.78585665 0.74572309]
 [1.25771443 0.88907472]
 [0.63459468 1.45133247]
 [0.42140669 0.30839562]
 [1.17363317 0.65281471]]


In [49]:
#45. Create random vector of size 10 and replace the maximum value by 0

import numpy as np

# Create a random vector of size 10
vector = np.random.random(10)

print("Original vector: ", vector)

# Replace the maximum value by 0
vector[vector.argmax()] = 0

print("Modified vector: ", vector)

Original vector:  [0.30782771 0.08405384 0.73725912 0.83121318 0.77048656 0.71697062
 0.39362286 0.93963052 0.2235696  0.54455079]
Modified vector:  [0.30782771 0.08405384 0.73725912 0.83121318 0.77048656 0.71697062
 0.39362286 0.         0.2235696  0.54455079]


In [50]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

import numpy as np

# Create a grid of points in the [0,1]x[0,1] area
x, y = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

# Create a structured array with x and y coordinates
structured_array = np.dstack([x, y])

print(structured_array)

[[[0.   0.  ]
  [0.25 0.  ]
  [0.5  0.  ]
  [0.75 0.  ]
  [1.   0.  ]]

 [[0.   0.25]
  [0.25 0.25]
  [0.5  0.25]
  [0.75 0.25]
  [1.   0.25]]

 [[0.   0.5 ]
  [0.25 0.5 ]
  [0.5  0.5 ]
  [0.75 0.5 ]
  [1.   0.5 ]]

 [[0.   0.75]
  [0.25 0.75]
  [0.5  0.75]
  [0.75 0.75]
  [1.   0.75]]

 [[0.   1.  ]
  [0.25 1.  ]
  [0.5  1.  ]
  [0.75 1.  ]
  [1.   1.  ]]]


In [51]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

import numpy as np

# Given two arrays, X and Y
X = np.arange(8)
Y = X + 0.5

# Construct the Cauchy matrix C
C = 1.0 / np.subtract.outer(X, Y)

print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


In [52]:
#48. Print the minimum and maximum representable value for each numpy scalar type

import numpy as np

# Integer types
for dtype in [np.int8, np.int16, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

# Floating types
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [53]:
#49. How to print all the values of an array?
import numpy as np

# Create an array
array = np.arange(100)

# Set the print options to print all values
np.set_printoptions(threshold=np.inf)

print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [54]:
#50. How to find the closest value (to a given scalar) in a vector?

import numpy as np

# Create a vector
vector = np.arange(100)

# Given a scalar
scalar = 57.1

# Find the closest value in the vector to the scalar
closest_value = vector[np.abs(vector - scalar).argmin()]

print(closest_value)

57


In [55]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
import numpy as np

# Create a structured data type
dtype = [('position', [('x', float, 1),
                       ('y', float, 1)]),
         ('color',    [('r', float, 1),
                       ('g', float, 1),
                       ('b', float, 1)])]

# Create a structured array
structured_array = np.array([((1.0, 2.0), (0.5, 0.5, 0.5)),
                             ((3.0, 4.0), (0.1, 0.2, 0.3))], dtype=dtype)

print(structured_array)

[((1., 2.), (0.5, 0.5, 0.5)) ((3., 4.), (0.1, 0.2, 0.3))]


/var/folders/9y/8rjmtst10lq0t833bkn_ks9w0000ks/T/ipykernel_24311/2731383050.py:12: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  structured_array = np.array([((1.0, 2.0), (0.5, 0.5, 0.5)),


In [56]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
import numpy as np

# Create a random vector with shape (100,2) representing coordinates
coordinates = np.random.random((100, 2))

# Compute the Euclidean distance between all pairs of points in the vector
distances = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates[np.newaxis, :, :], axis=-1)

print(distances)

[[0.         0.64959347 0.25035078 0.91170844 0.73687253 0.67136203
  0.90657768 0.44580801 0.67255207 0.64709998 0.67639561 0.58488959
  0.44745275 0.25630654 0.50469416 0.39893064 0.63069444 0.836364
  0.06712804 0.70170543 0.64666408 0.62237802 0.54454224 0.78093216
  0.04380423 0.59020163 0.86420056 0.4908406  0.27360055 0.70733947
  0.65101536 0.46837167 0.49857531 0.67091572 0.90433487 0.50845901
  0.18456289 0.86697213 0.30153488 0.09147498 0.59852255 0.06558052
  0.65372477 0.73057333 0.72640368 0.60903048 0.51084615 0.55099942
  0.83041353 0.71100801 0.25213495 0.24091049 0.74634731 0.74894855
  0.08793009 0.74829078 0.2761852  0.32356504 0.76302498 0.42146876
  0.82934418 0.30486011 0.79914486 0.30307155 0.18678752 0.66713489
  0.44346808 0.44128721 1.14382442 0.35821503 0.66275604 0.32222722
  0.51326787 0.18396972 0.79080779 0.44952266 0.73232414 0.1847095
  0.78398608 0.56366602 0.25983589 0.50288547 0.83936335 0.41434658
  1.05057551 0.76741779 0.56723766 0.4438764  0.625

In [57]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
import numpy as np

# Create a float (32 bits) array
array = np.array([1.0, 2.5, 3.3, 4.9], dtype=np.float32)

print("Original array: ", array)

# Convert the array into an integer (32 bits) in place
array = array.astype(np.int32)

print("Converted array: ", array)

Original array:  [1.  2.5 3.3 4.9]
Converted array:  [1 2 3 4]


In [62]:
#54. How to read the following file?
"""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""
import numpy as np
from io import StringIO

# Given file content
file_content = StringIO(
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
)

# Read the file
data = np.genfromtxt(file_content, delimiter=",", dtype=np.int, filling_values=0)

print(data)

SyntaxError: invalid syntax (2091665310.py, line 11)

In [63]:
#55. What is the equivalent of enumerate for numpy arrays?
import numpy as np

# Create a numpy array
array = np.array([[1, 2], [3, 4]])

# Use ndenumerate to iterate over items
for index, value in np.ndenumerate(array):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [64]:
#56. Generate a generic 2D Gaussian-like array

import numpy as np

# Define the 2D Gaussian function
def g(x, y, sigma=1.0):
    return np.exp(-((x**2 + y**2) / (2.0 * sigma**2)))

# Generate a grid of points
x, y = np.ogrid[-1:1:100j, -1:1:100j]

# Generate the 2D Gaussian-like array
gaussian_array = g(x, y)

print(gaussian_array)

[[0.36787944 0.37531033 0.38273509 0.39014747 0.39754112 0.40490961
  0.41224639 0.41954485 0.42679831 0.434      0.44114314 0.44822088
  0.45522635 0.46215266 0.46899291 0.4757402  0.48238765 0.4889284
  0.49535563 0.50166256 0.5078425  0.51388879 0.51979489 0.52555433
  0.53116077 0.53660796 0.54188982 0.54700038 0.55193383 0.55668454
  0.56124703 0.56561604 0.56978646 0.57375342 0.57751226 0.58105853
  0.58438803 0.58749679 0.59038109 0.59303746 0.59546272 0.59765394
  0.59960845 0.60132389 0.60279818 0.60402951 0.60501638 0.6057576
  0.60625224 0.60649972 0.60649972 0.60625224 0.6057576  0.60501638
  0.60402951 0.60279818 0.60132389 0.59960845 0.59765394 0.59546272
  0.59303746 0.59038109 0.58749679 0.58438803 0.58105853 0.57751226
  0.57375342 0.56978646 0.56561604 0.56124703 0.55668454 0.55193383
  0.54700038 0.54188982 0.53660796 0.53116077 0.52555433 0.51979489
  0.51388879 0.5078425  0.50166256 0.49535563 0.4889284  0.48238765
  0.4757402  0.46899291 0.46215266 0.45522635 0.44

In [65]:
#57. How to randomly place p elements in a 2D array?

import numpy as np

# Create a 2D array
array = np.zeros((10, 10))

# Number of elements to place
p = 5

# Randomly place p elements in the array
np.put(array, np.random.choice(range(10*10), p, replace=False), 1)

print(array)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [66]:
#58. Subtract the mean of each row of a matrix
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Subtract the mean of each row of the matrix
result = matrix - matrix.mean(axis=1, keepdims=True)

print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [67]:
#59. How to sort an array by the nth column?
import numpy as np

# Create an array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Column to sort by
n = 1

# Sort the array by the nth column
sorted_array = array[array[:,n].argsort()]

print(sorted_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
#60. How to tell if a given 2D array has null columns?
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])

# Check if the array has any null columns
has_null_columns = np.any(np.isnan(array), axis=0)

print(has_null_columns)

[False  True False]


In [69]:
#61. Find the nearest value from a given value in an array
# Create an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Given value
value = 5.4

# Find the nearest value in the array to the given value
nearest_value = array[np.abs(array - value).argmin()]

print(nearest_value)

5


In [70]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

import numpy as np

# Create two arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Compute their sum using an iterator
result = np.zeros((3,3))
it = np.nditer([array1, array2, result], flags=['multi_index'], op_flags=[['readonly'], ['readonly'], ['readwrite']])
for x, y, z in it:
    z[...] = x + y

print(result)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [71]:
#63.Create an array class that has a name attribute
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

# Create an instance of NamedArray
named_array = NamedArray(np.arange(10), "range_10")
print(named_array.name)

range_10


In [72]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)
import numpy as np

# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Second vector
index_vector = np.array([0, 1, 2, 2, 4])

# Add 1 to each element indexed by the second vector
np.add.at(vector, index_vector, 1)

print(vector)

[2 3 5 4 6]


In [74]:

#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

import numpy as np

# Given vector X
X = np.array([1, 2, 3, 4, 5])

# Index list I
I = np.array([1, 3, 3, 2, 4])

# Array F
F = np.zeros(10)

# Accumulate elements of X to F based on I
np.add.at(F, I, X)

print(F)


[0. 1. 4. 5. 5. 0. 0. 0. 0. 0.]


In [75]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

import numpy as np

# Create a (w,h,3) image of (dtype=ubyte)
image = np.random.randint(0, 256, (5, 5, 3), dtype=np.ubyte)

# Compute the number of unique colors
unique_colors = np.unique(image.reshape(-1, 3), axis=0)

print(len(unique_colors))

25


In [76]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
import numpy as np

# Create a four dimensions array
array = np.random.rand(3, 4, 5, 6)

# Get sum over the last two axis at once
sum_array = array.sum(axis=(-2,-1))

print(sum_array)

[[14.96315258 16.29541005 13.36559567 14.09607942]
 [14.62243157 14.80770558 14.87569819 13.26195765]
 [16.08030088 14.94847065 17.37011992 14.39768673]]


In [77]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
import numpy as np

# Given one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6])

# Vector S of same size describing subset indices
S = np.array([0, 1, 1, 2, 2, 2])

# Compute means of subsets of D using S
sums = np.bincount(S, weights=D)
counts = np.bincount(S)
means = sums / counts

print(means)

[1.  2.5 5. ]


In [78]:
#69. How to get the diagonal of a dot product?
import numpy as np

# Create two arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product
dot_product = np.dot(A, B)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[19 50]


In [79]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
import numpy as np

# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Create a new vector with 3 consecutive zeros interleaved between each value
new_vector = np.zeros(len(vector) + (len(vector)-1)*3)
new_vector[::4] = vector

print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [80]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 
import numpy as np

# Create an array of dimension (5,5,3)
array1 = np.random.rand(5, 5, 3)

# Create an array with dimensions (5,5)
array2 = np.random.rand(5, 5)

# Multiply array1 by array2
result = array1 * array2[..., np.newaxis]

print(result)

[[[0.00463508 0.35400399 0.29272742]
  [0.00521043 0.00587714 0.02740039]
  [0.28601601 0.10630808 0.20376258]
  [0.09277656 0.12901167 0.13429994]
  [0.15388378 0.17503026 0.26916195]]

 [[0.61322616 0.27239827 0.29008179]
  [0.39044822 0.65587732 0.24789158]
  [0.13279335 0.22289944 0.0643262 ]
  [0.12148846 0.13942845 0.24788204]
  [0.33854112 0.28156053 0.41201708]]

 [[0.11277534 0.08563234 0.10373816]
  [0.03686807 0.74530616 0.58051513]
  [0.28995541 0.77730394 0.0879167 ]
  [0.24514868 0.15161627 0.10033411]
  [0.12745271 0.09597085 0.01719659]]

 [[0.03536191 0.17599925 0.36999942]
  [0.00828371 0.00483008 0.00126149]
  [0.03511089 0.43395481 0.25695156]
  [0.16484244 0.02940187 0.16982043]
  [0.24685633 0.03940579 0.59102058]]

 [[0.01848691 0.12268514 0.17767806]
  [0.16912028 0.12853127 0.09507884]
  [0.07115424 0.09907219 0.06640202]
  [0.14549816 0.56102595 0.53689092]
  [0.07632105 0.04719714 0.05096895]]]


In [81]:
#72. How to swap two rows of an array?
import numpy as np

# Create an array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Swap rows 0 and 1
array[[0, 1]] = array[[1, 0]]

print(array)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [82]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
import numpy as np

# Set of 10 triplets describing 10 triangles
triplets = np.random.randint(0, 100, (10, 3))

# Find the set of unique line segments composing all the triangles
segments = set([tuple(sorted([i, j])) for i, j in np.roll(triplets.repeat(2, axis=1), -1, axis=1).reshape(-1, 2)])

print(segments)

{(45, 71), (24, 45), (72, 88), (49, 96), (69, 77), (59, 82), (78, 98), (9, 72), (37, 97), (35, 69), (32, 82), (24, 78), (76, 91), (27, 49), (87, 91), (29, 37), (3, 24), (24, 71), (35, 77), (76, 87), (47, 63), (24, 98), (63, 90), (29, 97), (32, 59), (47, 90), (2, 3), (27, 96), (9, 88), (2, 24)}


In [83]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

import numpy as np

# Given a sorted array C that corresponds to a bincount
C = np.array([1, 2, 3, 4, 5])

# Produce an array A such that np.bincount(A) == C
A = np.repeat(np.arange(len(C)), C)

print(A)

[0 1 1 2 2 2 3 3 3 3 4 4 4 4 4]


In [ ]:
#75. How to compute averages using a sliding window over an array?
import numpy as np

# Given array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Size of the sliding window
window_size = 3

# Compute averages using a sliding window
averages = np.convolve(array, np.ones(window_size), 'valid') / window_size

print(averages)

In [85]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
import numpy as np

# Given one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Build a two-dimensional array
result = np.lib.stride_tricks.sliding_window_view(Z, (3,))

print(result)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [86]:
#77. How to negate a boolean, or to change the sign of a float inplace?

# Negate a boolean
bool_val = True
bool_val = not bool_val

# Change the sign of a float inplace
float_val = 1.23
float_val *= -1

print(bool_val)
print(float_val)

False
-1.23


In [87]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

import numpy as np

# Given sets of points P0, P1 describing lines (2d)
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))

# Given point p
p  = np.random.uniform(-10, 10, (1, 2))

# Compute the distance from p to each line i (P0[i],P1[i])
d = np.abs(np.cross(P1-P0, P0-p)) / np.linalg.norm(P1-P0, axis=1)

print(d)

[4.18458426 3.6587524  5.82418593 2.56403305 1.97116885 1.1831094
 0.92313454 2.25579307 3.22954809 1.72907761]


In [88]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

import numpy as np

# Given sets of points P0, P1 describing lines (2d)
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))

# Given set of points P
P = np.random.uniform(-10, 10, (10, 2))

# Compute the distance from each point j (P[j]) to each line i (P0[i],P1[i])
d = np.abs(np.cross(P1-P0, P0-P[:, None])) / np.linalg.norm(P1-P0, axis=1)

print(d)

[[ 0.31642499  0.12204472  4.78981049  5.21907595  9.26199432  9.48999894
   5.48376993 15.64634703  2.34877683  3.00418177]
 [ 5.52317437  1.11115512 12.42624501  4.12531697  2.0327718   1.14945794
   1.6875851   7.75264623  5.6426617   3.68251464]
 [ 1.79576751  0.4532188   2.06839844  8.72559152 11.82023084 12.49863958
   8.28904261 18.69925214  0.92731421  2.54402547]
 [ 4.20186221  0.32563373 13.05333171  3.69039654  1.31608368  0.71193879
   0.57564487  8.73854834  4.22585868  2.24987984]
 [ 2.46677003  3.37415934  1.79253641  6.0035828  12.39450243 12.17037453
   4.21973736 14.82583526  5.10221776  6.30711348]
 [11.53607797 13.53462993  3.15748979  3.50587723 17.9560822  15.81649358
   3.234234    8.31485725 14.97322029 16.4578815 ]
 [ 2.90954537  4.24919244  8.18831643  4.8710992   5.65472847  6.56224684
   7.68314053 17.31277085  1.53328084  1.41130856]
 [ 4.92725802  4.41248648  4.75316131  8.85149628  8.92953274 10.26823643
  10.59352027 20.56046791  2.70194215  1.44030885]


In [119]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

def extract_subarray(array, center, shape, fill_value=0):
    # Pad the array
    array_padded = np.pad(array, [(dim//2, dim//2) for dim in shape], mode='constant', constant_values=fill_value)
    
    # Calculate the indices
    indices = np.ix_(*[range(i-(dim//2), i+(dim//2)+1) for i, dim in zip(center, shape)])
    
    # Extract the subarray
    subarray = array_padded[indices]
    
    return subarray

# Given an arbitrary array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Center and shape
center = (1, 1)
shape = (3, 3)

# Extract the subarray
subarray = extract_subarray(array, center, shape, fill_value=0)

print(subarray)

[[0 0 0]
 [0 1 2]
 [0 4 5]]


In [90]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
import numpy as np

# Given array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Generate an array R
R = np.lib.stride_tricks.sliding_window_view(Z, (4,))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [91]:
#82. Compute a matrix rank
import numpy as np

# Given matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print(rank)

2


In [92]:
#83. How to find the most frequent value in an array?
import numpy as np

# Given array
array = np.array([1, 2, 3, 2, 2, 4, 3, 4, 2, 1, 1, 1, 2])

# Find the most frequent value in the array
most_frequent = np.bincount(array).argmax()

print(most_frequent)

2


In [95]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

import numpy as np

# Given a random 10x10 matrix
matrix = np.random.rand(10, 10)

# Extract all the contiguous 3x3 blocks
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))

print(blocks)


[[[[3.12538687e-01 3.75126647e-01 9.78551599e-01]
   [8.31363306e-01 3.96066610e-01 9.88244402e-02]
   [4.19617193e-01 2.02773334e-01 8.53683502e-01]]

  [[3.75126647e-01 9.78551599e-01 1.65035471e-01]
   [3.96066610e-01 9.88244402e-02 3.81764929e-01]
   [2.02773334e-01 8.53683502e-01 9.44048102e-01]]

  [[9.78551599e-01 1.65035471e-01 9.64289000e-01]
   [9.88244402e-02 3.81764929e-01 8.10960013e-01]
   [8.53683502e-01 9.44048102e-01 4.15849170e-01]]

  [[1.65035471e-01 9.64289000e-01 7.37143959e-01]
   [3.81764929e-01 8.10960013e-01 4.75711652e-01]
   [9.44048102e-01 4.15849170e-01 1.11741558e-01]]

  [[9.64289000e-01 7.37143959e-01 3.09804100e-01]
   [8.10960013e-01 4.75711652e-01 6.74955167e-01]
   [4.15849170e-01 1.11741558e-01 2.86352948e-01]]

  [[7.37143959e-01 3.09804100e-01 3.76527759e-01]
   [4.75711652e-01 6.74955167e-01 3.23810936e-01]
   [1.11741558e-01 2.86352948e-01 7.32512421e-01]]

  [[3.09804100e-01 3.76527759e-01 8.96230472e-02]
   [6.74955167e-01 3.23810936e-01 8.03

In [96]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
import numpy as np

class Symmetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symmetric, self).__setitem__((i, j), value)
        super(Symmetric, self).__setitem__((j, i), value)

def symmetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symmetric)

# Create a 2D array
Z = np.random.randint(0, 10, (5, 5))

S = symmetric(Z)

print(S)

[[ 3 12 12  5  8]
 [12  1  8  9 10]
 [12  8  8 14 16]
 [ 5  9 14  0 10]
 [ 8 10 16 10  5]]


In [97]:
#86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

import numpy as np

# Given a set of p matrices with shape (n,n)
p_matrices = np.random.rand(5, 3, 3)

# Given a set of p vectors with shape (n,1)
p_vectors = np.random.rand(5, 3, 1)

# Compute the sum of the p matrix products at once
result = np.einsum('ijk,ikl->jl', p_matrices, p_vectors)

print(result)

[[2.54843646]
 [2.84977016]
 [3.19062201]]


In [98]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

import numpy as np

# Given a 16x16 array
array = np.random.rand(16, 16)

# Get the block-sum (block size is 4x4)
block_sum = array.reshape(4, 4, -1, 4).sum(axis=(1, 3))

print(block_sum)

[[8.68703611 5.98956441 9.07364314 7.82237347]
 [5.72303564 8.23023555 9.1870165  8.15272997]
 [8.512648   7.47212698 6.9962225  7.6722459 ]
 [6.12371159 6.70525231 8.23375672 7.39667306]]


In [ ]:
#88. How to implement the Game of Life using numpy arrays?

In [99]:
#89. How to get the n largest values of an array
import numpy as np

# Given array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Get the 3 largest values of the array
n_largest = np.flip(np.partition(array, -3)[-3:])

print(n_largest)

[10  9  8]


In [100]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
import numpy as np

def cartesian_product(*arrays):
    grids = np.meshgrid(*arrays, indexing='ij')
    dim = len(grids)
    shape = (dim, -1)
    cartesian = np.vstack([grid.reshape(-1) for grid in grids]).T
    return cartesian

# Given an arbitrary number of vectors
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7, 8, 9])]

# Build the cartesian product
product = cartesian_product(*vectors)

print(product)

[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 6]
 [3 5 7]
 [3 5 8]
 [3 5 9]]


In [101]:
#91. How to create a record array from a regular array?
import numpy as np

# Given a regular array
array = np.array([["Alice", 25, 55.0], ["Bob", 22, 62.1], ["Charlie", 20, 68.5]])

# Create a record array from the regular array
record_array = np.core.records.fromarrays(array.T, names='Name,Age,Weight')

print(record_array)

[('Alice', '25', '55.0') ('Bob', '22', '62.1') ('Charlie', '20', '68.5')]


In [102]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
import numpy as np

# Given a large vector Z
Z = np.random.rand(1000000)

# Method 1: Using the ** operator
Z1 = Z ** 3

# Method 2: Using the numpy power function
Z2 = np.power(Z, 3)

# Method 3: Using the numpy multiply function
Z3 = np.multiply(np.multiply(Z, Z), Z)

In [103]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 
import numpy as np

# Given two arrays A and B
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

# Find rows of A that contain elements of each row of B
rows = np.array([np.isin(A, B[i]).all(axis=1) for i in range(len(B))]).all(axis=0)

print(A[rows])

[]


In [104]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
import numpy as np

# Given a 10x3 matrix
matrix = np.random.randint(0, 5, (10, 3))

# Extract rows with unequal values
rows = matrix[~(matrix[:,1:] == matrix[:,:-1]).all(1)]

print(rows)

[[2 4 1]
 [0 1 1]
 [4 3 3]
 [0 1 2]
 [2 3 1]
 [4 0 4]
 [0 4 1]
 [0 3 1]
 [0 4 4]
 [1 0 0]]


In [105]:
#95. Convert a vector of ints into a matrix binary representation
import numpy as np

# Given a vector of ints
vector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

# Convert the vector of ints into a matrix binary representation
binary_matrix = np.unpackbits(vector[:, np.newaxis], axis=1)

print(binary_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [106]:
#96. Given a two dimensional array, how to extract unique rows?
import numpy as np

# Given a two-dimensional array
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [107]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
# Given 2 vectors A & B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Einsum equivalent of inner product
inner_product = np.einsum('i,i->', A, B)

# Einsum equivalent of outer product
outer_product = np.einsum('i,j->ij', A, B)

# Einsum equivalent of sum
sum_A = np.einsum('i->', A)
sum_B = np.einsum('i->', B)

# Einsum equivalent of multiplication
mul = np.einsum('i,i->i', A, B)

print("Inner product:", inner_product)
print("Outer product:\n", outer_product)
print("Sum of A:", sum_A)
print("Sum of B:", sum_B)
print("Multiplication:", mul)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A: 6
Sum of B: 15
Multiplication: [ 4 10 18]


In [112]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [109]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
import numpy as np

# Given an integer n and a 2D array X
n = 5
X = np.array([[1, 0, 4], [2, 3, 0], [1, 1, 3], [1.5, 1.5, 2], [2, 2, 2]])

# Select rows which only contain integers and which sum to n
rows = X[(np.mod(X, 1) == 0).all(1) & (X.sum(axis=1) == n)]

print(rows)


[[1. 0. 4.]
 [2. 3. 0.]
 [1. 1. 3.]]


In [110]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
 #Given a 1D array X
X = np.random.rand(100)

# Number of bootstrap samples
N = 1000

# Resample the elements of the array with replacement N times, compute the mean of each sample
means = np.array([np.mean(np.random.choice(X, len(X))) for _ in range(N)])

# Compute percentiles over the means
lower, upper = np.percentile(means, [2.5, 97.5])

print("95% confidence interval for the mean:", (lower, upper))

95% confidence interval for the mean: (0.4744616824898468, 0.5899461543443895)
